config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: :show

  resources :leagues
  
  root to: 'users#show'
end

app/models/concerns/scrapable.rb
module Scrapable
  extend ActiveSupport::Concern

  class_methods do

    def source(url)
      NokoGiri::HTML(open(url))
    end

    def container(descriptor)
      source.css descriptor
    end
  end
end

app/models/daily_result.rb
require 'nokogiri'
require 'open-uri'

class DailyResult < ActiveRecord::Base
  include Scrapable


  # attributes
  def player_table
    
  end

end

app/models/league.rb
require 'nokogiri'
require 'open-uri'

class League < ActiveRecord::Base
  has_many :memberships
  has_many :users, through: :memberships
  has_many :teams

  def collect_yearly_standings(year)
    doc = Nokogiri::HTML open("http://games.espn.go.com/flb/standings?leagueId=#{espn_id}&seasonId=#{year}")
    rows = doc.css 'table.tableBody tr.tableBody'
      
    rows[0..11].each do |row|
      attributes = team_espn_attributes row

      team = Team.find_or_initialize_by espn_id: attributes[:espn_id], league: self
      team.name = attributes[:name]
      team.save!

      wins_and_losses = row.elements[1..3]

      SeasonStanding.create! team: team, 
                             year: year, 
                             wins: wins_and_losses[0].text,
                             losses: wins_and_losses[1].text,
                             ties: wins_and_losses[2].text
    end
  end

  def collect_yearly_weekly_results(year)
    scoring_periods = (1..22).to_a

    scoring_periods.each { |scoring_period| collect_weekly_results year, scoring_period }
  end

  def collect_weekly_results(year, scoring_period)
    doc = Nokogiri::HTML open("http://games.espn.go.com/flb/scoreboard?leagueId=#{espn_id}&seasonId=#{year}&matchupPeriodId=#{scoring_period}")

    matchup_tables = doc.css 'table.matchup'

    matchup_tables.each do |matchup|
      first_team_info = matchup.elements[0]
      second_team_info = matchup.elements[1]

      first_team_url = first_team_info.css('a')[0]['href']
      second_team_url = second_team_info.css('a')[0]['href']

      first_team_espn_id = extract_team_espn_id_from_url first_team_url
      second_team_espn_id = extract_team_espn_id_from_url second_team_url

      WeeklyResult.create! team: teams.find_by(espn_id: first_team_espn_id),
                           opponent_id: second_team_espn_id,
                           points_scored: first_team_info.css('td').last['title'],
                           year: year,
                           scoring_period: scoring_period

      WeeklyResult.create! team: teams.find_by(espn_id: second_team_espn_id),
                           opponent_id: first_team_espn_id,
                           points_scored: second_team_info.css('td').last['title'],
                           year: year,
                           scoring_period: scoring_period      
    end
  end

  def weighted_season_standings
    standings = []

    teams.each do |team|
      standings << team.weighted_season_standings(2014)
    end

    standings.sort { |a, b| b[:weighted_wins] <=> a[:weighted_wins] }
  end

  def extract_team_espn_id_from_url(url)
    url.split('&teamId=')[1].split('&')[0]
  end

  def team_espn_attributes(nokogiri_row)
    team_url = nokogiri_row.css('a').first.attributes["href"].value
    team_id = team_url.split('&teamId=')[1].split('&').first
    team_name = nokogiri_row.css('a').first.attributes["title"].value.split(' (').first

    { espn_id: team_id, name: team_name }    
  end

  def sorted_lifetime_standings
    standings = []

    teams.each do |team|
      standings << team.lifetime_standings
    end

    standings.sort { |a, b| b[:wins] <=> a[:wins] }
  end
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :league
end

app/models/season_standing.rb
class SeasonStanding < ActiveRecord::Base
  belongs_to :team
end

app/models/sport.rb
class Sport < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :league
  has_many :season_standings
  has_many :weekly_results

  def lifetime_standings
    total_wins = season_standings.sum(:wins)
    total_losses = season_standings.sum(:losses)
    total_ties = season_standings.sum(:ties)

    { 
      name: name,
      wins: total_wins,
      losses: total_losses,
      ties: total_ties,
      winning_percentage: calculate_percentage(total_wins, (total_wins + total_losses + total_ties))
    } 
  end

  def weighted_lifetime_standings
    lifetime_hash = { name: name, weighted_wins: 0, actual_wins: 0, win_diff: 0, losses: 0, ties: 0 }

    years = [2011, 2012, 2013, 2014]

    years.each do |year|
      weighted_year = weighted_season_standings year
      binding.pry

      lifetime_hash[:weighted_wins] += weighted_year[:weighted_wins]
      lifetime_hash[:actual_wins] += weighted_year[:actual_wins]
      lifetime_hash[:win_diff] += weighted_year[:win_diff]
      lifetime_hash[:losses] += weighted_year[:losses]
      lifetime_hash[:ties] += weighted_year[:ties]
    end

    lifetime_hash
  end

  def weighted_season_standings(year)
    hash = { name: name, weighted_wins: 0, losses: 0, ties: 0 }

    weeks = weekly_results.where year: year

    other_teams = league.teams.reject { |team| team == self }

    weeks.each do |week|
      wins = 0
      losses = 0
      ties = 0

      other_teams.each do |other_team|
        points_scored = week.points_scored
        other_team_score = other_team.weekly_results.find_by(year: year, scoring_period: week.scoring_period).points_scored

        case
        when points_scored > other_team_score
          wins += 1
        when points_scored < other_team_score
          losses += 1
        when points_scored == other_team_score
          ties += 1
        end
      end

      hash[:weighted_wins] += (wins.to_f / other_teams.count.to_f)
      hash[:losses] += (losses.to_f / other_teams.count.to_f)
      hash[:ties] += (ties.to_f / other_teams.count.to_f)      
    end

    hash[:weighted_wins] = hash[:weighted_wins].round(3)
    hash[:losses] = hash[:losses].round(3)
    hash[:ties] = hash[:ties].round(3)

    standings = season_standings.find_by year: year
    hash[:win_diff] = (hash[:weighted_wins] - standings.wins).round(3)
    hash[:actual_wins] = standings.wins
    hash
  end

  def calculate_percentage(numerator, denominator)
    (numerator.to_f / denominator.to_f).round(3) 
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :memberships
  has_many :leagues, through: :memberships
end

app/models/weekly_result.rb
class WeeklyResult < ActiveRecord::Base
  belongs_to :team
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    user_path resource
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController

  before_action :authenticate_user!
  helper_method :league

  def new
    @league = League.new

  end

  def index
  end

  def show
  end

  def create
    @league = League.new league_params
    @user = current_user
    @membership = Membership.new league: @league, user: @user

    if @league.save && @membership.save
      redirect_to user_path(current_user), notice: 'League and membership saved!'
    else
      render :new
    end
  end

  private

  def league_params
    params.require(:league).permit(:name, :espn_id, :sport_id)
  end

  def league
    @league ||= League.find params[:id]    
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  before_action :authenticate_user!

  helper_method :all_sports

  def index
  end

  private

  def all_sports
    @all_sports ||= Sport.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  helper_method :current_user

  def show

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
%h1 This is some fantasy sports bullshit

.login-section
  - if user_signed_in?
    Logged in as
    %strong.email_address= current_user.email
    = link_to 'Edit Profile', edit_user_registration_path
    |
    = link_to "Logout", destroy_user_session_path, method: :delete
  - else
    = link_to 'Login', new_user_session_path
    |
    = link_to 'Sign Up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title PeoplesHistory
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %p.notice
      = notice
    %p.alert
      = alert
    = yield

app/views/leagues/new.html.haml
%h1 New League

= form_for @league, url: { action: 'create' } do |f|
  = f.text_field :name, placeholder: 'League name'
  = f.text_field :espn_id, placeholder: 'ESPN League ID'
  = f.text_field :sport_id, placeholder: 'Sport ID'
  = f.submit 'create league'

app/views/leagues/show.html.haml
#league-container
  %h1 
    = league.name
  .lifetime-standings-container
    %p Lifetime Standings
    %table.lifetime-standings
      %thead
        %th Team
        %th Wins
        %th Losses
        %th Ties
        %th Winning Percentage
      %tbody
        - league.sorted_lifetime_standings.each do |standing|
          %tr
            %td
              = standing[:name]
            %td
              = standing[:wins]
            %td
              = standing[:losses]
            %td
              = standing[:ties]
            %td
              = standing[:winning_percentage]

  .weighted-standings-container
    %p Weighted 2014 Standings
    %table.weighted-standings
      %thead
        %th Team
        %th Weighted Wins
        %th Actual Wins
        %th Differential
        %th Losses
        %th Ties
      %tbody
        - league.weighted_season_standings.each do |standing|
          %tr
            %td
              = standing[:name]
            %td
              = standing[:weighted_wins]
            %td
              = standing[:actual_wins]
            %td
              = standing[:win_diff]
            %td
              = standing[:losses]
            %td
              = standing[:ties]

%p League moments

%p Current stats

app/views/sports/index.html.haml
%h1 All sports

%ul
- all_sports.each do |sport|
  %li
    = sport.name  

app/views/users/show.html.haml
.login-section
  - if user_signed_in?
    Logged in as
    %strong.email_address= current_user.email
    = link_to 'Edit Profile', edit_user_registration_path
    |
    = link_to "Logout", destroy_user_session_path, method: :delete
  - else
    = link_to 'Login', new_user_session_path
    |
    = link_to 'Sign Up', new_user_registration_path

= link_to 'Add a league', new_league_path

%ul.leagues-list
  - current_user.leagues.each do |league|
    %li
      = link_to "#{league.name}", league_path(league.id)